name: maruthi_eats_admin
description: Maruthi Eats - Admin/Restaurant order management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_launcher_icons: ^0.14.4

  # Firebase
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_auth: ^6.5.7

  # UI
  google_fonts: ^8.2.1
  intl: ^0.20.3
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.8

  # Utils
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"


