// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVhC3t5e4A7zpiJvfbphyv1-VGCOU1Xyw',
    appId: '1:119948554671:web:c8a050aa0f5148d5b23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    authDomain: 'maruthi-eats.firebaseapp.com',
    storageBucket: 'maruthi-eats.firebasestorage.app',
    measurementId: 'G-GXDQRCTGK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlnBDuqrG9DiwdarS2H2iZXhr2IzAq1bM',
    appId: '1:119948554671:android:e1b3dbb30f28e1f7b23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    storageBucket: 'maruthi-eats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8p6vn59Zv7PuGKgKJUn661uGdRWCVuu8',
    appId: '1:119948554671:ios:a087639bd48aeeb0b23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    storageBucket: 'maruthi-eats.firebasestorage.app',
    iosBundleId: 'com.example.maruthiEatsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8p6vn59Zv7PuGKgKJUn661uGdRWCVuu8',
    appId: '1:119948554671:ios:a087639bd48aeeb0b23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    storageBucket: 'maruthi-eats.firebasestorage.app',
    iosBundleId: 'com.example.maruthiEatsAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVhC3t5e4A7zpiJvfbphyv1-VGCOU1Xyw',
    appId: '1:119948554671:web:0057060ab4d37193b23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    authDomain: 'maruthi-eats.firebaseapp.com',
    storageBucket: 'maruthi-eats.firebasestorage.app',
    measurementId: 'G-YSB7L65FBD',
  );
}
